### ISSUE TITLE
Tropecientos Muros De Golpe XD

### ISSUE THREAD

**Issue by bitt3rman** [Kalm004/onebuttonjam2016#1]
Acabo de descargar la última versión y al ejecutarla en Unity ¡genera un montón de muros de golpe y los "escupe" contra mi! ¿Activaste el modo hiper-hardcore? XD

Tengo la última versión de Unity y no le he metido mano a nada, en principio al abrirlo todo estaba ok XD

**Comment by Kalm004** [comment]
Se me olvidó subir un archivo, ya está corregido :+1:
