### ISSUE TITLE
Reducción de Rendimiento Según Pasan Muros

### ISSUE THREAD

**Issue by bitt3rman** [Kalm004/onebuttonjam2016#2]
Estoy notando bajadas de FPS a medida que voy pasando muros, probablemente se deba a que los que ya han pasado no se están destruyendo, ¿verdad?

**Comment by Kalm004** [comment]
Sí, exactamente, tengo pendiente de mejorar eso. Me pongo con ello.

**Comment by bitt3rman** [comment]
Curiosamente parece que también puede ser debido a el modelo de cubo que estoy usando importado de blender... Es un simple cubo de 1x1x1!

**Comment by bitt3rman** [comment]
Vale, he visto por qué no le gustaba mi cubo... Se me había olvidado configurar el prefab añadiéndole el box collider y el rigidbody. Una vez hecho eso, se comporta como el cubo que ya tenías (WallElement) y no noto problemas.

**Comment by Kalm004** [comment]
Hecho!
